### ISSUE TITLE
Performance issues when using certain regular expression

### ISSUE THREAD

**Issue by pgarciafc** [sford/yet-another-commit-checker#117]
Hi,

I'm using version 1.11 of YACC deployed into a Bitbucket Server 4.7.1.

This morning we changed the regular expression from "^(.[^Merge]|\n)_(Merge|([A-Z]+)-(\d+))(.|\n)_" to "^(.[^Merge]|[^Revert]|\n)_(Merge|Revert|([A-Z]+)-(\d+))(.|\n)_" and Bitbucket started queueing processes (pushes, pull requests, merges, etc), due to a huge increase in CPU usage. Once it reached 100%, Bitbucket crashed.

Although it is clear that the new regex is not optimal, I think it should not provoke such bad behaviour.

Have you been told about any similar issue?
Thanks,

**Comment by sford** [comment]
Hey @pgarciafc , no one has told me about any similar issues regarding regexes and YACC, however, [Stack Overflow recently experienced an outage caused by a regex change](http://stackstatus.net/post/147710624694/outage-postmortem-july-20-2016). So, it wouldn't surprise me that certain regexes can cause CPU spikes on pushes if a regex uses backtracking (like in the Stack Overflow issue).

**Comment by sford** [comment]
Closing as won't fix. I agree it isn't optimal that regex would cause problems, but it is a known issue with regexes that things like backtracking can be slow. So, assuming this is indeed related to the regex, I don't think YACC can do much to determine whether or not the regex will cause problems.
