### ISSUE TITLE
Unable to check JIRA issue

### ISSUE THREAD

**Issue by cmg1986** [sford/yet-another-commit-checker#127]
I am using JIRA6.4.12 & Bitbucket 4.9.1, created application linking & its working perfectly fine as able to traverse JIRA issue from commit screen. I have setup Oauth as authorization is done by Jira & i am an admin on both the instances.
So after enabling YACC, i just checked for "Require Valid Jira issue key", so when i am trying to push i get an error like below:

$ git push origin master
Counting objects: 3, done.
Writing objects: 100% (3/3), 244 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: Wrong ID
remote:
remote: refs/heads/master: 617cc563e9593252a1758c7f6d1d156690e92f7d: ATLAS-1040: JIRA Issue does not exist

While same issue exist even i am able to traverse from commit screen of stash with same user.
Please help !!

**Comment by agusmba** [comment]
Additional information would be useful:

* what is(are) the commit(s) comment(s) you are trying to push?
* what is the jql you configured in yacc to check the existence of the jira issue?

**Comment by cmg1986** [comment]
i am not using JQL, i choose just jira issue check.

**Comment by agusmba** [comment]
I don't remember if JQL is needed or not (I'm just a long term user), would you mind trying using a simple JQL such as
`project = ATLAS`

(please forgive me if the JQL syntax is not the right one, I don't have a Jira at hand atm).

**Comment by sford** [comment]
Hi @cmg1986 , is it possible for you to double check the user on JIRA that is being used via OAuth?   Maybe check JIRA access logs? Typically when you get that error, the issue doesn't exist or the user doesn't have permission to view that issue.

You can also try turning on [YACC debug logging](https://github.com/sford/yet-another-commit-checker#enable-logging) to see if it logs anything useful.

If that doesn't work, you could try the unreleased 1.12-SNAPSHOT from master branch... it has much better debug logging for JIRA communication that might indicate what the problem is.

**Comment by cmg1986** [comment]
Thanks @sford @agusmba, I checked Oauth configuration in Jira & after creating apllication linking again it is working perfectly fine.
