### ISSUE TITLE
Not able to save hook config due to "Issue JQL matcher" not valid

### ISSUE THREAD

**Issue by neuezg** [sford/yet-another-commit-checker#167]
Hello, I'm trying to implement a simple hook to check that a valid issue is provided.
But even with a simple jql query, the config won't save due to error "JQL: query is invalid"...
Why is that? 
Tested in Bitbucket 5.2.2 linked to JIRA7.2.8 with YACC 1.17
![capture](https://user-images.githubusercontent.com/31992328/30486790-da8f3434-9a31-11e7-8d3d-6041293605ce.JPG)

Regards
Gael

**Comment by sford** [comment]
Is TEST a valid project in your instance? YACC validates the query by
running it against your JIRA instance. That error could be triggered
because that project does not exist, or maybe you don't have permissions to
access it.

**Comment by neuezg** [comment]
Oh, I see, this means that at hook creation time, I must be a user having the necessary rights on jira to access the projects... As I tried it as a local bitbucket admin, I obvisouly don't have access to jira data.
But this means then that I must have a user that is admin on both apps to create the hook? 
Regards

**Comment by neuezg** [comment]
Then I have a question, when the user will commit, with which credentials are the JIRA info checked from the commit message?

**Comment by sford** [comment]
When the user commits, it should check the JIRA info for that user. Typically BBS<->JIRA authenticate is done through OAuth, so it should be the same user for both BBS and JIRA. If a JQL query is configured to require a certain project that user does not have access to in JIRA, pushes should fail because JIRA will return permission error.
