### ISSUE TITLE
Re-enable data center support tag within Atlassian Marketplace

### ISSUE THREAD

**Issue by sford** [sford/yet-another-commit-checker#205]
Atlassian removed data center tag for YACC on marketplace listing last month due to introducing new data center processes. Needs to get fixed.

**Comment by sford** [comment]
Hey @bturner, not sure if this is in your wheelhouse, but are you familiar with the data center changes Atlassian is currently doing? The data center support tag for YACC on the marketplace listing was removed around Nov 26th. I have had a DCHELP ticket open trying to figure out what needs to be done but not making a lot of progress. Do you know what needs to be done to fix this?

**Comment by bturner** [comment]
Sorry, @sford. I'm aware of the changes, but I'm not involved with the review process and don't have any insights into it. [This post](https://community.developer.atlassian.com/t/improvements-coming-to-data-center-apps-review-process/25409) (requires a community login) details some changes to the DC verification process, but that's pretty much everything I know.

**Comment by sford** [comment]
Thanks @bturner for the response, I really appreciate it.

I actually literally just got access to that post, which is really helpful. Just read through the comments... OUCH! I am glad this issue appears to be on Atlassian's radar.

**Comment by CptPlastic** [comment]
is this really broken for datacenter?

**Comment by sford** [comment]
@CptPlastic Not really, I should have clarified.

YACC has supported data center since 2015. Atlassian changed their data center policies in the Atlassian Marketplace and are now requiring an approval process.

Atlassian went ahead and stripped data center support from all plugins in Marketplace retroactively. This left anyone using plugins in their data center install in an awkward spot because they can't update plugins within BBS due to the "data center support" tag being removed. This could potentially prevent them from updating BBS if BBS indicates a plugin is not supported. If I understand correctly (at least, I am getting a ton of update requests!)

The Atlassian data center approval process that they started has a queue from weeks to months to get an app approved to be installed in a data center installation via the marketplace. 

I believe YACC should work if the plugin is downloaded and install manually (not via their marketplace integration thing within BBS):
https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker/version-history
I haven't tried this though.

**Comment by gsylvie** [comment]
The process also requires vendors (including free vendors like @sford here!) must spin up large multi-node Bitbucket Data Center instances and load-test them before & after installing their add-on.

On the one hand it makes a lot of sense, since Bitbucket installs are pretty vulnerable to flaky resource intensive add-ons.

But on the other hand, it creates a tonne of work for add-on developers like @sford - and he's not exactly getting paid.

**Comment by bturner** [comment]
@gsylvie The process of getting Data Center certified isn't required for anyone. If @sford feels it's too much of a time investment for something he's doing on the side, he can opt to not do it. He'd "just" forego having a "Data Center" label on Marketplace.

I think everyone needs to acknowledge that there's no "perfect" solution. The old approach for Data Center compatibility was, quite simply, flawed in its very premise. Any add-on developer could declare their add-on to be Data Center compatible by adding a single line in their `atlassian-plugin.xml` _with no further investment on their part._ Why wouldn't everyone do it, when there's no effort involved? There was no oversight, no actual verification. Developers didn't have to test their add-ons with Data Center at all in order to set the property. In the end, an add-on being marked as Data Center compatible meant almost nothing--and proved absolutely nothing. The result of that laxness has been pretty poor for Data Center administrators and end users; installing an add-on that _claimed_ to be Data Center compatible could (and often did) destabilize or outright cripple the system.

The new process isn't only time-consuming for vendors (and how time-consuming it is for them strongly depends on how much investment they've already made in _actually_ verifying their add-ons in a Data Center installation, and setting up tooling/infrastructure to support that); it's very time-consuming for _Atlassian_ too. But add-ons that go through the process are often substantially improved over their state at the time of submission. I can't speak too much for Data Center verification in other products, but the Bitbucket Server developers who have been reviewing submissions have helped vendors make significant performance and scalability improvements to their add-ons, as well as pointing out gaps in the testing that has been done that concealed bugs and limitations. It's been a valuable process for many, if not all of them. And Data Center administrators, and their users, will reap the benefits of those enhancements.

@sford has been great to work with, for me, and as a result I've offered a fair amount of help with this add-on, both in the form of my own patches and in the form of responding to mentions and reviewing other patches--largely on my own time. That said, though, if the Data Center verification process represents an unacceptable drain on his time, I, for one, completely understand that. That's why it's optional. He could absolutely opt to skip the process, close this issue, and forego the Data Center certification. Of course, that means Data Center installs won't see his app listed on the Marketplace and won't readily be able to install it. But I think that's a fair trade-off.

Data Center certification is about setting expectations, not just verifying the quality of an add-on. If a vendor doesn't have the time, or the desire, to put forward the effort to be certified, _Data Center administrators deserve to know that before they install that vendor's add-on(s)._ If the process forces vendors who haven't otherwise invested in much tooling around Data Center testing to do so, again, for the Data Center administrators who will be installing their add-ons and caring for the system afterward, and for the end users whose experience stands to be significantly impacted by misbehaving add-ons, that seems like a pretty clear win. If a vendor doesn't have the time to get certified, they likely don't have the ability to respond in a timely fashion if their add-on causes an issue on a Data Center installation used by thousands of developers.

I hope the process for @sford will be as straightforward as it can be. When he mentioned me here, I responded. And I've done what I can to facilitate the process, bringing this issue up with the developers who are doing the reviews for certification. I absolutely apologize for the way the changeover from the old process to the new process has been handled (even though, to be clear, _I was not, and am not, involved with that change_). Unfortunately, though, there's not a lot I personally can do about it. Vendors haven't been thrilled with how things were handled, and they've made that clear. Hopefully improvements can be made to the process going forward. I think we all have the same end goal in mind: A better experience for Data Center administrators and their users.

**Comment by sford** [comment]
YACC has successfully gone through the Atlassian DC approval review process, and is now marked as supported again on the Atlassian Marketplace.

@bturner, I appreciate all the help and attention you have given to YACC over the years. Especially with the migration to BBS 5.0 APIs. Your time and help is greatly appreciated. Thank you!
