### ISSUE TITLE
JQL to check that assignee = current committer

### ISSUE THREAD

**Issue by wilsonjean** [sford/yet-another-commit-checker#44]
What variables are available to the hook and the JQL text box that I can put into the JQL to verify that assignee of jira issue is the same as the author?

**Comment by sford** [comment]
Hi @wilsonjean ,

YACC executes the JQL query as-is, it doesn't do anything special or provides replacement variables.

JQL has a `currentUser()` function though [1]. Assuming you are using OAuth authentication (so that Stash is executing JQL as the user doing the push), you can do `assignee=currentUser()`. See #36 for more info.

[1] https://confluence.atlassian.com/display/JIRA/Advanced+Searching
