### ISSUE TITLE
Issue JQL Matcher: JQL Query Syntax is invalid

### ISSUE THREAD

**Issue by pphilbey** [sford/yet-another-commit-checker#56]
The configuration is not allowing us to apply settings to the Issue JQL matcher. Rather, applying even simple settings like `project = "AB100_ABC"` doesn't work.

`The JQL query syntax is invalid.` is returned instead on the configuration page. Note that "Require valid JIRA issue(s)" is selected, and "Ignore Unknown JIRA project keys" is unselected.

**Comment by sford** [comment]
Followup questions: Does `project = "AB100_ABC"` work if you search for that in JIRA? Does `assignee is not empty` work if you put that into YACC? Does `Require valid JIRA issue(s)` work without configuring a JQL matcher?

Just off the top of my head, I could see `project = "AB100_ABC"` returning `The JQL query syntax is invalid.` (which really is just saying that JIRA returned a 400 when YACC tries to execute that JQL query) in a couple situations:

* The user that Stash is using to talk to JIRA does not have permission to view that project
* That project doesn't exist in the primary JIRA application link Stash is using

Checking whether or not `assignee is not empty` works would point you in the direction of what to check next because it wouldn't be affected by permission or project not existing issues.

**Comment by sford** [comment]
Going to close this, but feel free to re-open if you are hitting the same problem in the latest version of YACC.

**Comment by pphilbey** [comment]
Hi, thank you for closing the issue. eventually we found that actually the issue was due to some other misconfiguration with our server settings. It was misleading as it was ultimately yacc that was throwing this error, but something like this is difficult to be accounted for.

Note to developers that may also be receiving this error: Check that Stash is correctly linked to Jira!
