### ISSUE TITLE
Branch Name Regex

### ISSUE THREAD

**Issue by alex131290** [sford/yet-another-commit-checker#57]
Hi I'm trying to use this regex: master|(?:(?:bugfix|hotfix|feature|develop)/[A-Z]+-\d+-.+)
Unfortunately it doesn't allow me to push the commits to the develop branch.

This is the error that i got:
refs/heads/develop: Invalid branch name. 'develop' does not match regex 'master|(?:(?:bugfix|hotfix|feature|myFeature|develop)/[A-Z]+-\d+-.+)'

**Comment by sford** [comment]
Your regex doesn't accept/match `develop` (pretty much what the error says). You have develop in there but it will only match something like `develop/ABC-123-abc`, not `develop` by itself.

If you want to allow just `develop`, you will need to tweak your regex. You can test you regex here: http://regexpal.com/. You will probably need to add `|develop`, similar to what you did with `master`.

**Comment by alex131290** [comment]
Thanks, I've figured out how to write it, i have another question, let's say that i'm not allowing user to push to the master, which means that i'm not including it in the regex, i'm gettiing into a problem, i'm as the admin of the project can't push either.

**Comment by sford** [comment]
If you want to disallow users to push to master, I think you should use Stash's branch permissions  (https://confluence.atlassian.com/display/STASH/Using+branch+permissions). So, put `master` back into the regex; however, you would be relying on Stash to reject the push to master depending on whatever branch permissions you have configured.

**Comment by alex131290** [comment]
I've added a public key of of one of the developers to the project, while i was conneted with my account, once the user tried to push, he got an error :
refs/heads/devel: 8aa4698a3b2dd648552c4d87235db45350591b34: expected committer email 'Alexander.Brodov@arris.com' but found 'ian.rabinowitz@arris.com'
but the user who made the push is : ian.rabinowitz@arris.com and not me.
How are you checking in your code who is the user in Stash ?

**Comment by sford** [comment]
Hey @alex131290 ,

> How are you checking in your code who is the user in Stash ?

Stash itself tells YACC who the user is. See https://github.com/sford/yet-another-commit-checker/blob/master/src/main/java/com/isroot/stash/plugin/YaccServiceImpl.java#L74

Basically, on push, the user authenticates to Stash, and then Stash provides the `StashUser` object to the hook which contains the user's login and email address.

> I've added a public key of of one of the developers to the project, while i was conneted with my account, 

If you added the public key while connected to your account, then I am guessing that public key is bound to your account. Essentially, this is giving permission to your developer to push code on your behalf because the developer is authenticating with your account.

**Comment by sford** [comment]
Closing. Feel free to re-open if you have other questions.
