### ISSUE TITLE
 IssueKey {xxxxx-3107} : JIRA Issue does not match JQL Query: status="IN DEVELOPMENT"

### ISSUE THREAD

**Issue by kkp1225** [sford/yet-another-commit-checker#59]
Our Stash version 2.10.1
Our Jira version (v6.2#6252-sha1:aa34325)

I have configured Yet Another Commit Checker plugin

Version:
1.1
Developer:
Sean Ford
Add-on key:
com.isroot.stash.plugin.yacc

Issue Jql Matcher: status = "IN DEVELOPMENT"

But its not working

ERROR IssueKey {xxxxx-3107} : JIRA Issue does not match JQL Query: status="IN DEVELOPMENT"

Even though we have jira issue "xxxxxx-3107" has right status="IN DEVELOPMENT".

After making changes to the JQL query as below.

Issue Jql Matcher: project in "xxxxx" and status = "IN DEVELOPMENT"

It worked. But problem here is developers works on different jira projects, I dont want to hard code those projects names inside each repo hooks.

Can you guys help me on this ?

**Comment by sford** [comment]
Hey @kkp1225 ,

It sounds like you are hitting a bug where YACC might not find the issue when running a JQL query that returns >50 results. The reason I think that is because it works for you when you add `project in ...`, which should cause it to return less results. You can verify this by searching for `status="IN DEVELOPMENT"` in JIRA and seeing if it returns >50 results.

This bug was fixed in YACC 1.3. So, you can try upgrading to the latest version of YACC. If you can't upgrade YACC, you are going to have to just workaround the bug.

As you mentioned, adding `project in` is not ideal, however, there are other options that **might** be better for you depending on your workflows. You just need to add something to restrict the result set:

* `assignee is not empty`
* `assignee is currentUser()`
* `updatedDate > -2w` <-- assuming developers are pushing to recent tickets... you can play around with the date range as you see fit

**Comment by sford** [comment]
Going to close, this but feel free to re-open if you are still experiencing this problem in the latest version of YACC.
