### ISSUE TITLE
Feature request: support multiple JIRA servers

### ISSUE THREAD

**Issue by caspark** [sford/yet-another-commit-checker#94]
`src/main/java/com/isroot/stash/plugin/JiraServiceImpl.java` assumes that the primary JIRA applink is the only JIRA applink, which means that commits can contain a valid issue on a non-primary-applink'd JIRA server but the hook errors with `JIRA Issue does not exist`.

The fix for this would be to use `ApplicationLinkService#getApplicationLinks(java.lang.Class<? extends ApplicationType> type)` to check all the JIRA applinks. If done in parallel (e.g. parallel stream + `anyMatch()`) this should be no slower than the current code in the happy case, but of course will be as slow as the slowest JIRA server in the case where the issue cannot be found. Would you be open to a PR along those lines? (subject to finding the time etc!)

Even if that's not something you're interested in supporting, multiple JIRA servers are relatively common in bigger organizations so it'd be helpful to document the limitation.

**Comment by preflightsiren** [comment]
:+1:

**Comment by sford** [comment]
Hey @caspark and @preflightsiren , yeah I would be open to a PR! I agree, this would be valuable. You might want to take a look at #28 which actually is supposed to support this but it hasn't been fully battle tested. If you guys review and test it, I can merge it.

Also, I noticed you guys are from Atlassian :-) How would you guys test a feature like this? YACC has decent unit test coverage, and I recently added integration testing using the Atlassian webdriver/page object framework. Is it easy or possible test multiple JIRA servers in something other than a unit test? 

Cheers :beer:

**Comment by caspark** [comment]
Sorry, been super busy and haven't had a chance to have a crack at this or take a good look at #28 yet (though initial impressions are that #28 checks JIRAs in series which might slow down our pushes too much - we have at least 5 JIRA servers connected to Bitbucket). We are indeed from Atlassian - that was a quick pickup!

Personally I'd primarily rely on unit tests for a change like this, as long as the portion that actually gets JIRA API responses is separate from the logic of interpreting/combining the responses, so that responses can be mocked more easily - chiefly because it's a pain (and slow) to spin up multiple copies of an app to test against and seed them with test data. I'd consider using wiremock or the like to get some fake JIRA responses since the JIRA API is plenty stable but likely wouldn't bother if I can get away with unit tests.

If it was a major feature of "cannot ever break" importance then we'd have a daily bamboo build which would actually set up several (likely just 2) JIRAs; the way that's usually done is restoring JIRA backups (in xml form, living alongside the tests) either by driving the web interface with webdriver or using test helper resources in a dedicated plugin (not sure which is actually used for JIRA in practice as most of my development has been on [Crowd](https://www.atlassian.com/software/crowd/overview/), but it follows the same testing patterns). So I don't have any easy answers for full stack integration testing, unfortunately!

**Comment by sford** [comment]
@soodsaks, @drcollatz, @marlang, @caspark, @preflightsiren:

Hey guys, you have all expressed interest in support for multiple JIRA servers for YACC. I wanted to let you know that I just pushed up a private YACC beta that includes support for multiple JIRA servers:

http://marketplace-cdn.atlassian.com/files/artifact/bb73e6e8-186c-4c5c-9ba9-26813b90d1f7/yacc-1.12-SNAPSHOT.jar

I have done a lot of local testing, but because I don't use multiple JIRA servers in production, I am not super comfortable releasing this publicly until I get some feedback from other users. Multiple JIRA support is actually pretty complicated due to having to handle a lot of different error conditions (developers might not have access to all JIRA instances, JQL queries might only be valid on certain instances, etc). So, I would really appreciate if you guys could give this version a test drive to see how it works.

This snapshot is based on PR #106.

Thanks!

**Comment by sford** [comment]
Fixed in 1.12
